# Github Workflow
# Creates a draft release whenever a tag with v* is added

name: generate_draft_release

on:
  push:
    tags:  
      - "v*"

permissions:
  contents: write

jobs:
  make-artifacts:
    name: Build artifacts
    uses: ./.github/workflows/build.yml
    with:
      upload-artifacts: true

  make-release:
    needs: make-artifacts
    name: Consolidate and upload
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3

      - name: List artifacts
        run: ls -R ${{steps.download.outputs.download-path}}

      - name: Strip binaries
        run: |
          strip ${{steps.download.outputs.download-path}}/Linux/salmonstats
          # TODO: figure out how to strip other binaries
          # strip ${{steps.download.outputs.download-path}}/macOS/salmonstats
          # strip ${{steps.download.outputs.download-path}}/Windows/salmonstats

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          draft: true
          artifacts: ${{steps.download.outputs.download-path}}/*/*, CHANGELOG.md
          body: "AUTOGENERATED: FILL BEFORE RELEASE"
