# Github Workflow
# Creates a draft release whenever a tag with v* is added

name: add_artifacts_to_release

on:
  push:
    branches: [main, release/*]
    tags:  
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Consolidate and upload
    runs-on: ubuntu-latest

    steps:
      - name: build artifacts
        uses: ./.github/workflows/build.yml
        with:
          upload-artifacts: true

      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: Display artifacts
        run: ls -R

